version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --ISCAgent false -b /rcc/src/pre.sh
    restart: always
    ports: 
      - 41773:1972
      - 42773:52773
    volumes:
      - ./:/rcc
